# Generated by Django 4.2.5 on 2023-09-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Question Title')),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('correct_answer', models.TextField(verbose_name='Correct Answer')),
                ('incorrect_answer1', models.TextField(blank=True, default='Bad answer 1', verbose_name='Incorrect Answer 1')),
                ('incorrect_answer2', models.TextField(blank=True, default='Bad answer 2', verbose_name='Incorrect Answer 2')),
                ('comment', models.TextField(blank=True, default='Your answer is wrong.', verbose_name='Comment')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Time of last update')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Test Title')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Time of last update')),
                ('questions', models.ManyToManyField(to='education.question', verbose_name='Questions in Test')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Course Title')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Time of last update')),
                ('tests', models.ManyToManyField(to='education.test', verbose_name='Tests in Course')),
            ],
        ),
    ]
