# Generated by Django 4.2.5 on 2024-01-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_coursesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=800, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.ImageField(blank=True, upload_to='course_icon/', verbose_name='Course Icon'),
        ),
    ]
