# Generated by Django 4.2.5 on 2024-01-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_course_description_course_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=340, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=40, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Time of last update')),
                ('file', models.FileField(blank=True, upload_to='content')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.course', verbose_name='Content in Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
