# Generated by Django 4.2.5 on 2024-01-20 15:07

from django.db import migrations, models
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_course_options_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(upload_to=education.models.course_directory_path, verbose_name='Content File'),
        ),
    ]
