# Generated by Django 4.2.5 on 2024-01-24 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0006_alter_content_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_score', models.FloatField(blank=True, default=0, verbose_name='Course Progress (/100)')),
                ('course_passed', models.BooleanField(default=False, verbose_name='Course is done (Yes/No)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Time of last update')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
        migrations.AlterField(
            model_name='coursesubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_score', models.FloatField(blank=True, default=0, verbose_name='Test Progress (/100)')),
                ('test_passed', models.BooleanField(default=False, verbose_name='Test is done (Yes/No)')),
                ('course_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.courseattempt', verbose_name='Course Attempt ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.test', verbose_name='Test Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_passed', models.BooleanField(default=False, verbose_name='Answer is correct (Yes/No)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.question', verbose_name='Question')),
                ('test_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.testattempt', verbose_name='Test Attempt ID')),
            ],
        ),
    ]
