# Generated by Django 4.2.5 on 2024-01-24 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_courseattempt_alter_coursesubscription_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubscription',
            name='course_passed',
            field=models.BooleanField(default=False, verbose_name='Course is done (Yes/No)'),
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='course_score',
            field=models.FloatField(blank=True, default=0, verbose_name='Course Progress (/100)'),
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of last update'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='course_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.coursesubscription', verbose_name='Course Attempt ID'),
        ),
        migrations.DeleteModel(
            name='CourseAttempt',
        ),
    ]
