# Generated by Django 4.2.5 on 2024-01-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_questionattempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='answer',
            field=models.TextField(default='test answer', verbose_name='Given Answer'),
            preserve_default=False,
        ),
    ]
