# Generated by Django 4.2.5 on 2024-02-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_questionattempt_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='end_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Test End Time'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Test Start Time'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='test_score',
            field=models.FloatField(blank=True, default=0, verbose_name='Test Progress (%)'),
        ),
    ]
